services:
  redis:
    image: redis:8-alpine
    restart: unless-stopped
    ports:
      - '6378:6379'
    # command: redis-server --requirepass $3CR3T
    volumes: 
      - cache:/data

volumes:
  cache:
    driver: local